name: Reusable Deploy

on:
  workflow_call:
    inputs:
      artifact_name:
        description: "Name of the artifact to deploy"
        required: true
        default: dist-files
        type: string

jobs:
  deploy:
    outputs:
      final-result: ${{ steps.result-output.outputs.data }}
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}

      - name: Deploy Application
        run: echo "Deployingg application..."
      
      - name : See Result Output
        id: result-output
        run : echo "::set-output data="Deployed Successfully""